### ISSUE TITLE
String::trim is supported by all major browsers

### ISSUE THREAD

**Issue by jcubic** [piecioshka/node-slice#5]
It's been a long time when you don't need to implement your own trim with regex:

See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim).

You can see support on [Can I use](https://caniuse.com/mdn-javascript_builtins_string_trim) It's even supported by IE10.

**Comment by piecioshka** [comment]
Thanks for your feedback. Have a great day!
